import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Characters, GetCharactersResults } from "../types";

const Home: NextPage<{ characters: Characters[] }> = ({ characters }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {characters.map((character) => {
        return (
          <>
            <li key={character.id}>{character.name}</li>
            <Image
              src={character.image}
              alt={character.name}
              width="200"
              height="200"
            />
          </>
        );
      })}
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const { results }: GetCharactersResults = await res.json();

  return {
    props: {
      characters: results,
    },
  };
};

export default Home;
